---
# tasks file for polkit
- name: Getting package facts
  package_facts:

- name: Checking version for polkit
  debug: 
    msg: "{{ ansible_facts.packages['polkit'][0].name }}-{{ansible_facts.packages['polkit'][0].version}}{{ansible_facts.packages['polkit'][0].release}}"
  register: installed_pkg

- set_fact:
    pkg: installed_pkg.msg

- name: Checking if system is vulnerable
  debug:
    msg: " {{ ansible_hostname }} is vulnerable"
  when: item == installed_pkg.msg
  loop: "{{ version }}"

# Including patch.yml for vulnerable systems
- name: Include patch task
  include_tasks:
    file: patch.yml
  when: item == installed_pkg.msg
  loop: "{{ version }}"